### ISSUE TITLE
分隔 ass Dialogue 的正则表达式可以优化

### ISSUE THREAD

**Issue by xiaokesheng** [zhangliangming/Subtitle#2]
ass中的Dialogue如下:

> Dialogue: 0,0:00:02.00,0:00:07.00,Default,,0000,0000,0001,,{\fn华文楷体\fs16\1c&H3CF1F3&\b0}--==本影片由 {\1c&HFF8000&\b1}CMCT 团队{\fn华文楷体\1c&H3CF1F3&\b0} 荣誉出品==--\N更多精彩影视 请访问 {\fnCronos Pro Subhead\1c&HFF00FF&\b1}http://cmct.cc{\r}

源码中分隔正则表达式如下

> Dialogue\S\s+\d+,\d+:\d+:\d+.\d+,\d+:\d+:\d+.\d+,\S+,

如果 zh 或 en 字幕中出现,的话，则使用split分隔，会得不到正确的结果。
代码在 AssSubtitleFileReader#parseSubtitleString 中。在正则表达式最后加一个,可以解决该问题。

**Comment by zhangliangming** [comment]
@xiaokesheng 的确存在这个问题。谢谢
